### PR TITLE
update javascript dependencies

### LINKED ISSUE #324: Update all JavaScript dependencies
The js dependencies we use can all be updated. Some of them even a major version with breaking changes. Updating them is always a good idea to also eliminate all the security warnings. It will also fix the github action.

### PR DESCRIPTION
**Pull request by jannaahs**
This will update all the javascript dependencies.

I've updated `tailwindcss` to the latest version and moved from the deprecated `node-sass` to `sass`.

No errors or warnings when building the frontend.

### CODE REVIEW

**Comment by knoxfighter** [comment]
My plan is to update all dependencies to the latest MAJOR version. That will surely break things.
So please update that as well.

**Comment by jannaahs** [comment]
> My plan is to update all dependencies to the latest MAJOR version. That will surely break things. So please update that as well.

@knoxfighter Yeah, I wanted that as well. I tried to look into the MapGenerator again and noticed we could need an update of the dependencies.
I'll probably need some time to figure out why the github action is failing, because I can build the frontend locally. I just ask for the code review so you know about it and don't start doing it as well :smile:

**Comment by knoxfighter** [comment]
Ah, i see, could have created is as DraftPR :)
The `npm` failed previously for windows only, cause of the update to VS2022, but now that the ubuntu is failing, you have to look yourself.

**Comment by jannaahs** [comment]
It seems to be related to tailwindcss. I'll have a look at it tomorrow or so.

**Comment by jannaahs** [comment]
@knoxfighter you can now have a look at it.

**Comment by louisza** [comment]
@knoxfighter is this ready to be pushed to the develop branch?

**Comment by knoxfighter** [comment]
Writing it down now, since i currently have a look at it and will fix this the following weeks: The update of react-router from v5 to v6 changed the fundamentals completely, therefore i have to rewrite everything that does something with routes (which is most of it ...)

**Comment by knoxfighter** [comment]
> Writing it down now, since i currently have a look at it and will fix this the following weeks: The update of react-router from v5 to v6 changed the fundamentals completely, therefore i have to rewrite everything that does something with routes (which is most of it ...)

Wasn't that bad, got a working UI again now :partying_face:

**Comment by knoxfighter** [comment]
If anybody wants to have another look, i would love the feedback.
In either case, i will merge this PR on Tuesday.

**Comment by Mattie112** [comment]
I can try it out but not before the weekend :) But we can always test in production ;)

**Comment by knoxfighter** [comment]
@Mattie112 I merge this PR now, i would love if you test the changes on the `develop` branch. You can either answer here, in a new issue, or on our discord, thank you :)

**Comment by Mattie112** [comment]
Did not notice any issues 👍

**Pull request merged**
