### PR TITLE
fix download URL in docker build due to project move

### PR DESCRIPTION
**Pull request by MichaelPereira**
quick fix to allow the docker build to download the release package since the project has been moved under a new owner

### CODE REVIEW

**Comment by MichaelPereira** [comment]
I just realized that there is a lot of rework happening on the develop branch with the same problem over there. To avoid conflicts, I can PR this same change over there as well (seems to be a fast-forward operation locally), since it would likely be quite disruptive to rebase nearly a year's worth of commits.

Sorry I didn't realize it sooner @knoxfighter but now I'm eager to try out all these improvements to the docker side of the project :)

**Comment by mroote** [comment]
Thanks for the PR @MichaelPereira

**Comment by mroote** [comment]
I tried switching the target branch to develop but we have had a few changes in that dockerfile since. Could you make the same change in the develop branch?

**Comment by knoxfighter** [comment]
I have fixed that merging error.  We also provide the current develop branch as docher images on the dockerhub, so you don't need to build the image yourself: `ofsm/ofsm:develop`

**Comment by knoxfighter** [comment]
I forgot to merge this, it is now fixed with PR #200

**Pull request closed without merging**
